# Production environment overrides
replicaCount: 3

image:
  repository: "517811334008.dkr.ecr.us-east-1.amazonaws.com/megamart-shopcore/order-service"
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

env:
  APP_VERSION: "production"
  NODE_ENV: "production"
  AWS_REGION: "us-east-1"
  ORDER_TABLE_NAME: "megamart-shopcore-dev-orders"

serviceAccount:
  roleArn: "arn:aws:iam::517811334008:role/megamart-shopcore-dev-order-service"

rollout:
  enabled: false
