# Dev environment overrides
replicaCount: 1

image:
  repository: 984449730427.dkr.ecr.us-east-1.amazonaws.com/order-service
  tag: 3e0b6fd75464944607f442fcb53421da8ccfc97b

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

env:
  APP_VERSION: "dev"
  NODE_ENV: "development"
