# Dev environment overrides
replicaCount: 1

image:
  repository: 517811334008.dkr.ecr.us-east-1.amazonaws.com/megamart-shopcore/order-service
  tag: 25b236e113a3f4607ccb3598d1d0b214b0fa49d2

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

env:
  APP_VERSION: "dev"
  NODE_ENV: "development"
  AWS_REGION: "us-east-1"
  ORDER_TABLE_NAME: "megamart-shopcore-dev-orders"

serviceAccount:
  roleArn: "arn:aws:iam::517811334008:role/megamart-shopcore-dev-order-service"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6

ingress:
  enabled: true
  host: "shopcore.example.com"
